@url = http://localhost:3000

###
GET {{url}}/signup HTTP/1.1
content-type: application/json

###
POST {{url}}/signup HTTP/1.1
content-type: application/json

{
  "email":"angelorubin@gmail.com",
  "password":"test",
  "role": "admin",
  "access_token": null
}
