@url = http://localhost:3000
GET {{url}}/signup HTTP/1.1
content-type: application/json

###
POST {{url}}/signup HTTP/1.1
content-type: application/json

{
  "email":"angelorubin@gmail.com",
  "password":"master77",
  "role": null,
  "access_token": null
}