@url = http://localhost:3000

###
GET {{url}}/vaccine
content-type: application/json

###
POST {{url}}/vaccine
content-type: application/json

{
  "nome_vacina": "a",
  "nome_fabricante": "a",
  "pais_origem": "a",
  "quantidade_minimas_doses": "a",
  "percentual_eficacia_comprovada": "a",
  "preco_venda_por_dose": "a"
}

###
GET {{url}}/vaccine/37
content-type: application/json

###
PATCH {{url}}/vaccine/37
content-type: application/json

{
  "nome_vacina": "a"
}
