@url = http://localhost:3001

###
GET {{url}}/vaccine
content-type: application/json

###
POST {{url}}/vaccine
content-type: application/json

{
  "nomeVacina": "a",
  "nomeFabricante": "a",
  "paisOrigem": "a",
  "quantidadeMinimasDoses": "a",
  "percentualEficaciaComprovada": "a",
  "precoVendaPorDose": "a"
}

###
GET {{url}}/vaccine/37
content-type: application/json

###
PATCH {{url}}/vaccine/37
content-type: application/json

{
  "nome_vacina": "a"
}
