@url = http://localhost:3001/vaccine
@id = 156

###
GET {{url}}/
content-type: application/json

###
POST {{url}}/
content-type: application/json

{
  "nomeVacina": "a",
  "nomeFabricante": "a",
  "paisOrigem": "a",
  "quantidadeMinimasDoses": "a",
  "percentualEficaciaComprovada": "a",
  "precoVendaPorDose": "a"
}

###
GET {{url}}/{{id}}
content-type: application/json

###
PATCH {{url}}/{{id}}
content-type: application/json

{
  "nome_vacina": "a"
}

###
PUT {{url}}/{{id}}
content-type: application/json