@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDgzMTI3MjUsImV4cCI6MTY0ODM5OTEyNX0.yrlCrksXnJGDoU1vzr97FFRMxGjq_9myAAuiOtqghYM

###
POST {{url}}/signin 
content-type: application/json
authorization: Bearer {{token}}

{
  "email":"test@test.com",
  "password":"test"
}
