@url = http://localhost:3000

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsImlhdCI6MTY0ODU3ODExNCwiZXhwIjoxNjQ4NjY0NTE0fQ.6EfKQmVGGrynZlv3jhpndAPxyX2C1w1iG6hbGX7JKEI

###
POST {{url}}/signin 
content-type: application/json
authorization: Bearer {{token}}

{
  "email":"test@test.com",
  "password":"test"
}
