@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0NzM3MTMwMCwiZXhwIjoxNjQ3NDU3NzAwfQ.qAX1DJWbtLRurUC339tqWChwDzj1-1sCn_X7RjSetKw

###
POST {{url}}/signin 
content-type: application/json
authorization: Bearer {{token}}

{
  "email":"test@test.com",
  "password":"test"
}
